'use server';

import { createServerSupabaseClient, createServiceRoleClient } from '@/lib/supabase/server';
import { getSiteURL } from '@/lib/site-url';
import type { Profile, OrgMembership } from '@/types/database';

// join_code is generated by the generate_org_join_code() DB trigger as
// upper(substring(md5(...) from 1 for 6)) — md5 hex output, so valid codes
// are always 6 uppercase hex characters (0-9, A-F).
const JOIN_CODE_PATTERN = /^[0-9A-F]{6}$/;

export interface AuthSignUpMetadata {
  first_name: string;
  last_name: string;
  role?: 'superadmin' | 'org_admin' | 'manager' | 'employee';
}

/**
 * Sign in with email and password
 */
export async function signInWithEmail(email: string, password: string) {
  try {
    const supabase = await createServerSupabaseClient();

    const { data, error } = await supabase.auth.signInWithPassword({
      email,
      password,
    });

    if (error) {
      return {
        success: false,
        error: error.message,
        data: null,
      };
    }

    return {
      success: true,
      error: null,
      data: data.user,
    };
  } catch (error) {
    return {
      success: false,
      error: error instanceof Error ? error.message : 'An error occurred',
      data: null,
    };
  }
}

/**
 * Sign up with email, password, and metadata
 */
export async function signUpWithEmail(
  email: string,
  password: string,
  metadata: AuthSignUpMetadata
) {
  try {
    const supabase = await createServerSupabaseClient();

    const { data, error } = await supabase.auth.signUp({
      email,
      password,
      options: {
        data: {
          first_name: metadata.first_name,
          last_name: metadata.last_name,
          role: metadata.role || 'employee',
        },
        // Where the confirmation email link lands after Supabase verifies
        // the token. Resolves to localhost in dev and the deployed Vercel
        // URL in production — see getSiteURL().
        emailRedirectTo: `${getSiteURL()}/auth/confirm?next=/dashboard`,
      },
    });

    if (error) {
      return {
        success: false,
        error: error.message,
        data: null,
      };
    }

    return {
      success: true,
      error: null,
      data: data.user,
    };
  } catch (error) {
    return {
      success: false,
      error: error instanceof Error ? error.message : 'An error occurred',
      data: null,
    };
  }
}

/**
 * Send a one-time-password "magic link" sign-in email.
 * The link lands on /auth/confirm, which exchanges the token for a
 * session and redirects to the dashboard.
 */
export async function signInWithMagicLink(email: string) {
  try {
    const supabase = await createServerSupabaseClient();

    const { error } = await supabase.auth.signInWithOtp({
      email,
      options: {
        emailRedirectTo: `${getSiteURL()}/auth/confirm?next=/dashboard`,
      },
    });

    if (error) {
      return { success: false, error: error.message };
    }

    return { success: true, error: null };
  } catch (error) {
    return {
      success: false,
      error: error instanceof Error ? error.message : 'An error occurred',
    };
  }
}

/**
 * Send a password-reset email. The link lands on /auth/confirm?next=/reset-password,
 * which exchanges the token for a recovery session before the user picks a new password.
 */
export async function requestPasswordReset(email: string) {
  try {
    const supabase = await createServerSupabaseClient();

    const { error } = await supabase.auth.resetPasswordForEmail(email, {
      redirectTo: `${getSiteURL()}/auth/confirm?next=/reset-password`,
    });

    if (error) {
      return { success: false, error: error.message };
    }

    return { success: true, error: null };
  } catch (error) {
    return {
      success: false,
      error: error instanceof Error ? error.message : 'An error occurred',
    };
  }
}

/**
 * Update the current user's password. Called from /reset-password once a
 * recovery session has been established via /auth/confirm.
 */
export async function updatePassword(newPassword: string) {
  try {
    const supabase = await createServerSupabaseClient();

    const { error } = await supabase.auth.updateUser({ password: newPassword });

    if (error) {
      return { success: false, error: error.message };
    }

    return { success: true, error: null };
  } catch (error) {
    return {
      success: false,
      error: error instanceof Error ? error.message : 'An error occurred',
    };
  }
}

/**
 * Sign in with SSO provider
 */
export async function signInWithSSO(
  provider: 'google' | 'azure' | 'okta'
) {
  try {
    const supabase = await createServerSupabaseClient();

    // Map provider names to Supabase supported providers
    let supabaseProvider: 'google' | 'azure' = provider === 'okta' ? 'azure' : provider;

    const { data, error } = await supabase.auth.signInWithOAuth({
      provider: supabaseProvider,
      options: {
        redirectTo: `${getSiteURL()}/auth/sso-callback`,
      },
    });

    if (error) {
      return {
        success: false,
        error: error.message,
        url: null,
      };
    }

    return {
      success: true,
      error: null,
      url: data?.url,
    };
  } catch (error) {
    return {
      success: false,
      error: error instanceof Error ? error.message : 'An error occurred',
      url: null,
    };
  }
}

/**
 * Sign out the current user
 */
export async function signOut() {
  try {
    const supabase = await createServerSupabaseClient();

    const { error } = await supabase.auth.signOut();

    if (error) {
      return {
        success: false,
        error: error.message,
      };
    }

    return {
      success: true,
      error: null,
    };
  } catch (error) {
    return {
      success: false,
      error: error instanceof Error ? error.message : 'An error occurred',
    };
  }
}

/**
 * Get the current session
 */
export async function getSession() {
  try {
    const supabase = await createServerSupabaseClient();

    const {
      data: { session },
      error,
    } = await supabase.auth.getSession();

    if (error) {
      return {
        success: false,
        error: error.message,
        session: null,
      };
    }

    return {
      success: true,
      error: null,
      session,
    };
  } catch (error) {
    return {
      success: false,
      error: error instanceof Error ? error.message : 'An error occurred',
      session: null,
    };
  }
}

/**
 * Get the current user's profile
 */
export async function getCurrentProfile(): Promise<{
  success: boolean;
  error: string | null;
  profile: Profile | null;
  membership: OrgMembership | null;
}> {
  try {
    const supabase = await createServerSupabaseClient();

    const {
      data: { user },
      error: userError,
    } = await supabase.auth.getUser();

    if (userError || !user) {
      return {
        success: false,
        error: userError?.message || 'No user found',
        profile: null,
        membership: null,
      };
    }

    // Fetch profile
    const { data: profileData, error: profileError } = await supabase
      .from('profiles')
      .select('*')
      .eq('id', user.id)
      .maybeSingle();

    if (profileError) {
      return {
        success: false,
        error: profileError.message,
        profile: null,
        membership: null,
      };
    }

    // Fetch membership
    const { data: membershipData } = await supabase
      .from('org_memberships')
      .select('*')
      .eq('user_id', user.id)
      .maybeSingle();

    // Membership might not exist, so we don't treat this error as critical
    return {
      success: true,
      error: null,
      profile: profileData as Profile,
      membership: membershipData as OrgMembership | null,
    };
  } catch (error) {
    return {
      success: false,
      error: error instanceof Error ? error.message : 'An error occurred',
      profile: null,
      membership: null,
    };
  }
}

/**
 * Redeem a join code to become an employee of an organisation.
 *
 * This is the server-side counterpart to the /complete-profile join-code
 * form. It must run here (not as a direct client-side Supabase call)
 * because the `organizations` RLS policy only grants SELECT to existing
 * members — a brand-new user has no membership yet, so an anon/authenticated
 * client query for the org by join_code would always return zero rows no
 * matter how valid the code is. The service-role client bypasses that and
 * lets us validate the code (format + existence) server-side, as required.
 */
export async function joinOrganizationByCode(
  joinCode: string,
  firstName: string,
  lastName: string
): Promise<{ success: boolean; error: string | null; orgName?: string }> {
  try {
    const normalizedCode = joinCode.trim().toUpperCase();

    if (!JOIN_CODE_PATTERN.test(normalizedCode)) {
      return { success: false, error: 'Invalid join code format. Codes are 6 characters (0-9, A-F).' };
    }

    const trimmedFirst = firstName.trim();
    const trimmedLast = lastName.trim();
    if (!trimmedFirst || !trimmedLast) {
      return { success: false, error: 'First and last name are required.' };
    }

    const supabase = await createServerSupabaseClient();
    const {
      data: { user },
      error: userError,
    } = await supabase.auth.getUser();

    if (userError || !user) {
      return { success: false, error: 'You must be signed in to join an organisation.' };
    }

    const service = await createServiceRoleClient();

    // Existence check — service role bypasses the members-only RLS policy.
    const { data: org, error: orgError } = await service
      .from('organizations')
      .select('id, name')
      .eq('join_code', normalizedCode)
      .maybeSingle();

    if (orgError) {
      return { success: false, error: 'Could not validate that code right now. Please try again.' };
    }
    if (!org) {
      return { success: false, error: 'Invalid join code. Please check with your organisation admin.' };
    }

    // Don't let an already-onboarded user silently re-join / switch orgs
    // through this form.
    const { data: existingMembership } = await service
      .from('org_memberships')
      .select('id')
      .eq('user_id', user.id)
      .maybeSingle();

    if (existingMembership) {
      return { success: false, error: 'You already belong to an organisation.' };
    }

    // Trigger normally creates the profile row on signup — upsert keeps
    // this resilient and records the name the user just entered.
    const { error: profileError } = await service.from('profiles').upsert({
      id: user.id,
      email: user.email ?? '',
      first_name: trimmedFirst,
      last_name: trimmedLast,
      role: 'employee',
      is_active: true,
    });

    if (profileError) {
      return { success: false, error: profileError.message };
    }

    const { error: membershipError } = await service.from('org_memberships').insert({
      user_id: user.id,
      org_id: org.id,
      org_role: 'employee',
    });

    if (membershipError) {
      return { success: false, error: membershipError.message };
    }

    return { success: true, error: null, orgName: org.name as string };
  } catch (error) {
    return {
      success: false,
      error: error instanceof Error ? error.message : 'An error occurred',
    };
  }
}
