import { NextRequest, NextResponse } from 'next/server';
import { createClient } from '@supabase/supabase-js';
import { createServerClient } from '@supabase/ssr';
import { cookies } from 'next/headers';

const serviceClient = createClient(
  process.env.NEXT_PUBLIC_SUPABASE_URL!,
  process.env.SUPABASE_SERVICE_ROLE_KEY!,
  { auth: { autoRefreshToken: false, persistSession: false } }
);

async function requireSuperadmin() {
  const cookieStore = await cookies();
  const supabase = createServerClient(
    process.env.NEXT_PUBLIC_SUPABASE_URL!,
    process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY!,
    { cookies: { getAll: () => cookieStore.getAll(), setAll: () => {} } }
  );

  const { data: { user } } = await supabase.auth.getUser();
  if (!user) return null;

  const { data: profile } = await serviceClient
    .from('profiles')
    .select('role')
    .eq('id', user.id)
    .maybeSingle();

  if (profile?.role !== 'superadmin') return null;
  return user;
}

// GET — list all organisations (with join codes for superadmins)
export async function GET() {
  const user = await requireSuperadmin();
  if (!user) return NextResponse.json({ message: 'Forbidden' }, { status: 403 });

  const { data, error } = await serviceClient
    .from('organizations')
    .select('id, name, domain, join_code, created_at')
    .order('name', { ascending: true });

  if (error) return NextResponse.json({ message: error.message }, { status: 500 });

  return NextResponse.json({ organizations: data ?? [] });
}

// POST — create a new organisation
export async function POST(request: NextRequest) {
  const user = await requireSuperadmin();
  if (!user) return NextResponse.json({ message: 'Forbidden' }, { status: 403 });

  try {
    const { name, domain } = await request.json();

    if (!name?.trim()) {
      return NextResponse.json({ message: 'Organisation name is required' }, { status: 400 });
    }

    const cleanDomain = domain?.trim() ? domain.trim().replace(/^@/, '').toLowerCase() : null;

    // join_code is auto-generated by the DB trigger
    const { data: org, error } = await serviceClient
      .from('organizations')
      .insert({ name: name.trim(), domain: cleanDomain })
      .select('id, name, domain, join_code')
      .single();

    if (error) {
      const msg = error.message.toLowerCase();
      if (msg.includes('unique') && msg.includes('domain')) {
        return NextResponse.json({ message: 'An organisation with this domain already exists.' }, { status: 409 });
      }
      return NextResponse.json({ message: error.message }, { status: 500 });
    }

    return NextResponse.json({ organization: org }, { status: 201 });
  } catch (err) {
    console.error('[POST /api/superadmin/organizations]', err);
    return NextResponse.json({ message: 'Internal server error' }, { status: 500 });
  }
}
